### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by Leeds-eBooks** [ajile/word-jumper#10]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (C:\Users\Ben\AppData\Local\atom\app-0.182.0\resources\app\src\atom.js:54:11)
Object.activate (C:\Users\Ben\Dropbox\Software\.atom\packages\word-jumper\lib\word-jumper.coffee:141:9)
```

**Comment by maxnowack** [comment]
+1
